# Generated by Django 5.0 on 2024-08-30 23:39

import django.db.models.deletion
import modules.investments.funds.validator
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, validators=[modules.investments.funds.validator.validate_fund_name], verbose_name='name')),
                ('buy_date', models.DateField(verbose_name='buy date')),
                ('buy_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='buy value')),
                ('currently_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='currently value')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funds', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'fund',
                'verbose_name_plural': 'funds',
            },
        ),
    ]
