[project]
name = "heart-of-gold"
version = "0.0.1"
dependencies = [
    "Django==5.0",
    "django-environ==0.11.2",
    "djangorestframework==3.15.2",
]

[project.optional-dependencies]
dev = ["poethepoet"]

[tool.poe.tasks]
clean = "rm -rf build && rm -rf heart_of_gold.egg-info"
manage = "src/manage.py"
