# Generated by Django 5.0 on 2024-08-25 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(max_length=10, unique=True, verbose_name='ticket')),
            ],
            options={
                'verbose_name': 'ticket',
                'verbose_name_plural': 'tickets',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, unique=True, verbose_name='note number')),
                ('net_value', models.IntegerField(verbose_name='net value')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'invoice',
                'verbose_name_plural': 'invoices',
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'tax',
                'verbose_name_plural': 'taxes',
            },
        ),
        migrations.CreateModel(
            name='InvoiceTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(verbose_name='value')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to='stocks.invoice', verbose_name='invoice')),
                ('tax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_taxes', to='stocks.tax', verbose_name='tax')),
            ],
            options={
                'verbose_name': 'invoice tax',
                'verbose_name_plural': 'invoice taxes',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_type', models.CharField(choices=[('BUY', 'buy'), ('SALE', 'sale')], max_length=10, verbose_name='stock type')),
                ('specification', models.CharField(blank=True, default='', max_length=100, verbose_name='specification')),
                ('is_fractioned', models.BooleanField(verbose_name='is fractioned')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('unit_price', models.IntegerField(verbose_name='unit price')),
                ('price', models.IntegerField(verbose_name='price')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='stocks.invoice', verbose_name='invoice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='stocks.ticket', verbose_name='ticket')),
            ],
            options={
                'verbose_name': 'stock',
                'verbose_name_plural': 'stocks',
            },
        ),
    ]
