# Generated by Django 5.0 on 2024-08-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CumulativeReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('cumulated_return', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='cumulated return')),
            ],
            options={
                'verbose_name': 'cumulative return',
                'verbose_name_plural': 'cumulative returns',
            },
        ),
    ]
